apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prasadapp1
  name: prasadapp1
  namespace: prasad-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prasadapp1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prasadapp1
    spec:
      containers:
      - image: prasads697/ashumobi:appv2
        name: ashumobi
        ports:
        - containerPort: 80
        resources: {}
        imagePullPolicy: Always
        env:
        - name : deploy
          value : app2

## add secvice with nodeport
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prasadsvc1
  name: prasadsvc1
  namespace: prasad-project
spec:
  ports:
  - name: 1923-80
    port: 1923
    protocol: TCP
    targetPort: 80
  selector:
    app: prasadapp1
  type: NodePort
status:
  loadBalancer: {}
